const Routes = {
  backoffice: {
    prefix: "/backoffice",
    base: "/",
    inventory: "/inventory",
    users: "/users",
    productsAdd: "/inventory/productsAdd",
    discount: "/discount",
  },
  client: {
    prefix: "/client",
    base: "/",
    register: "/sign-up",
    login: "/log-in",
    workerRegister: "/sign-up-employee",
    workerLogin: "/log-in-employee",
    shop: "/shop",
    new: "/new",
    profile: "/profile",
    category: "/shop/:category",
    product: "/shop/:category/:productId",
    individualProduct: "/product/:productId",
    newProducts: "/new/:productId",
    wishlist: "/wishlist",
    collectionProduct: "/collection/:productId",
    checkout: "/checkout",
    shoppingBag: "/shopping-bag",
    orderHistory: "/order-history",
    return: "/order-history/:orderId/return",
  },
  company: {
    prefix: "/company",
    base: "/",
    register: "/sign-up",
    login: "/log-in",
    pending: "/pending",
    active: "/active",
  },
};

export default Routes;
