export enum QueryKey {
  USER_AUTHENTICATION = "USER_AUTHENTICATION",
  GET_PRODUCTS_BY_FILTER_QUERY = "GET_PRODUCTS_BY_FILTER_QUERY",
  GET_CLIENT_ORDERS_HISTORY = "GET_CLIENT_ORDERS_HISTORY",
  FIND_PRODUCT_BY_ID = "FIND_PRODUCT_BY_ID",
  MAKE_ORDER_RETURN = "MAKE_ORDER_RETURN",
  FIND_ORDER_BY_ID = "FIND_ORDER_BY_ID",
  REGISTER_CLIENT = "REGISTER_CLIENT",
  LOGIN_CLIENT = "LOGIN_CLIENT",
  CREATE_PRODUCT = "CREATE_PRODUCT",
  GET_COLORS = "GET_COLORS",
}
